/*==============================================================================

name:       SquareByRenderCSS.java

purpose:    Three By Three Square whose style is dynamically generated by css.

history:    Sat Oct 27, 2018 10:30:00 (Giavaneers - LBM) created

notes:
                        COPYRIGHT (c) BY GIAVANEERS, INC.
         This source code is licensed under the MIT license found in the
             LICENSE file in the root directory of this source tree.

==============================================================================*/
                                       // package --------------------------- //
package io.reactjava.client.examples.threebythree.state;

                                       // imports --------------------------- //
import io.reactjava.client.core.react.Component;

                                       // SquareByRenderCSS ==================//
public class SquareByRenderCSS extends Component
{
                                       // class constants ------------------- //
                                       // (none)                              //
                                       // class variables ------------------- //
                                       // public instance variables --------- //
                                       // (none)                              //
                                       // protected instance variables -------//
                                       // (none)                              //
                                       // private instance variables -------- //
                                       // (none)                              //
/*------------------------------------------------------------------------------

@name       render - render component
                                                                              */
                                                                             /**
            Render component. This implementation includes only markup.

@return     void

@history    Sat Oct 27, 2018 10:30:00 (Giavaneers - LBM) created

@notes
                                                                              */
//------------------------------------------------------------------------------
public final void render()
{
   useState("color", "blue");
                                       // use Paper instead of div to allow   //
                                       // non-string parameter 'clickhandler" //
                                       // to be passed as a property by parent//
                                       // which can't be done for div         //
/*--
   <@material-ui.core.Paper onClick={props().get("clickhandler")} />
--*/
};
/*------------------------------------------------------------------------------

@name       renderCSS - get component css
                                                                              */
                                                                             /**
            Get component css.This implementation is all css, with no java
            code included.

@return     void

@history    Sat Oct 27, 2018 10:30:00 (Giavaneers - LBM) created

@notes

                                                                              */
//------------------------------------------------------------------------------
public void renderCSS()
{
/*--
   {cssSelectorForId()}
   {
      padding-top: 100%;
      background-color: {getStateString("color")};
   }
--*/
}
}//====================================// end SquareByRenderCSS ==============//
